config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'reviews#all'
  resources :reviews
  devise_for :users
  devise_scope :user do
    match '/sign-in' => "devise/sessions#new", :via => [:get], :as => :login
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  ratyrate_rateable 'rating'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to login_path, :notice => 'Please Login!'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :only => [:new, :index]
  # GET /reviews
  # GET /reviews.json
  def index
    if user_signed_in?
      @reviews = Review.where(:user_id => current_user.id)
    else
      @reviews = Review.all
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    params.require(@review).permit(:pros, :cons, :category)
  end

  # GET /reviews/1/edit
  def edit
  end
  
  def all
    #if user_signed_in?
    #  @userreviews = Review.where(:user_id => current_user.id)
    #end
    @reviews = Review.all
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @cuser = current_user.id
    @review = Review.new(review_params)
    
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :description, :rating, :dogfriendly, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rovers Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <div class="background-image"></div>
  <ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
  <nav class="deep-orange accent-2" role="navigation">
    <div class="nav-wrapper container"><%= image_tag("logo.png", :alt => "logo") %>
      <ul class="right hide-on-med-and-down">
          <% if user_signed_in? %>
            <li><%= link_to 'New Review', new_review_path %></li>
            <li><%= link_to 'My Reviews', reviews_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
    </div>
  </nav>
  <ul id="slide-out" class="side-nav">
    <li><div class="userView">
      <div class="background">
      </div>
      <a href="#!user"><%= image_tag("logo.png", :alt => "logo") %></a>
      <a href="#!name"><span class="white-text name">John Doe</span></a>
      <a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a>
    </div></li>
    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
    <li><a href="#!">Second Link</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Subheader</a></li>
    <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
  </ul>
<div class="container-fluid">
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
  <%= yield %>
</div>
</body>
</html>

app/views/reviews/_form.html.erb
<div class="container">
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <p class="flow-text">Name</p>
    <%= f.text_field :name, :class => "grey lighten-2" %>
  </div>
  <div class="field">
    <p class="flow-text">Category</p>
    <%= f.text_field :category, :class => "grey lighten-2 autocomplete", :id => "autocomplete-input", %>
  </div>
  <div class="field">
    <p class="flow-text">Pros, Woof Woof</p><br>
    <%= f.text_area :pros, :class => "materialize-textarea grey lighten-2" %>
  </div>
  <div class="field">
    <p class="flow-text">Cons, Bone to pick</p><br>
    <%= f.text_area :cons, :class => "materialize-textarea grey lighten-2" %>
  </div>
  <div class="field">
    <p class="flow-text">Description</p>
    <%= f.text_area :description, :class => "materialize-textarea grey lighten-2" %>
  </div>
  <div class="field">
    <p class="flow-text">Rating</p>
    <div class="col-sm-6" id='star-rating'></div>  
  </div>
  </br>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit 'Submit', :class => "waves-effect waves-light btn" %>
  </div>
<% end %>
</div>
<script>
$('#star-rating').raty({
    path: '/assets',
    scoreName: 'review[rating]'
});
$(document).ready(function(){
  $('input.autocomplete').autocomplete({
    data: {
	  "Products": null,
	  "Services": null,
	  "Stores": null,
	  "Restraunts": null,
	  "Parks": null,
	  "Events": null,
	  "Shelters": null,
	  "Hotels": null
	}
  });
});

</script>

app/views/reviews/all.html.erb
<div class="container">
  <h1>Reviews</h1>
  <% if user_signed_in? %>
    <%= link_to 'New Review', new_review_path %>
    </br>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
    </br>
    <%= link_to 'My Reviews', reviews_path %>
    </br>
       <% if @reviews.present? %>
           <% @reviews.each do |review| %>
              <%= review.name %>
           <% end %>
       <% end %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path %></br>
    <%= link_to 'Sign Up', new_user_registration_path %>
  <% end %>
        <tbody>
          <% @reviews.each do |post| %>
            <tr>
              <td><h2><%= post.name %></h2></td>
              <td><%= truncate(post.description, :length => 20) %></td>
              <td><%= link_to 'View', post %></td>
              <% if user_signed_in? %>
                <% if post.user_id = current_user.id %>
                  <td><%= link_to 'Edit', edit_review_path(post) %></td>
                  <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>
    

app/views/reviews/edit.html.erb
<div class="container">
    <h2>Edit</h2>
</div>
<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Reviews</h1>

<% if user_signed_in? %>
  <%= link_to 'Home', root_path %>
  </br>
  <%= link_to 'New Review', new_review_path %>
  </br>
  <%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
  </br>
     <% if @reviews.present? %>
         <% @reviews.each do |review| %>
            <%= review.name %>
            <td><%= link_to 'View', review %></td>
            <td><%= link_to 'Edit', edit_review_path(review) %></td>
            <td><%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
     <% end %>
<% end %>

<br>

app/views/reviews/new.html.erb
<div class="container">
    <h2>New Review</h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
  <%= @review.category %>
  <%= @review.pros %>
  <%= @review.cons %>
  <%= @review.description %>
</p>

<p>
  <div class="star-rating" data-score= <%= @review.rating %> ></div>
</p>


<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>
<% if user_signed_in? %>
  <% if @review.user_id = current_user.id %>
    <%= link_to 'Edit', edit_review_path(@review) %> |
    <%= link_to 'Delete', @review, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
<% end %>
<%= link_to 'Back', root_path %>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>